---
- hosts: 172.31.5.13, 172.31.8.119
  become: true
  tasks:
  - name: I want to execute direct linux command
    command: hostname -f
    register: myfirstresult

  - name: I want to debug my first tasks
    debug:
       msg: "{{myfirstresult}}"