---
- hosts: 172.31.5.13, 172.31.8.119
  become: true
  tasks:
  - name: I want to execute direct linux command
    command: hostname -f
    register: myfirstresult
    when: ansible_os_family in ["Debian", "RedHat"]

  - name: I want to debug my first tasks
    debug:
       msg: "{{myfirstresult}}"

  - name: I want to install tree
    apt:
      name: tree
      state: present
    when: myfirstresult.stderr!=""

  - name: I want to install wget
    apt:
      name: wget
      state: present
    when: myfirstresult.stderr==""
  #when: ansible_os_family in ["Debian", "RedHat"]
    