---
- hosts: 172.31.5.13
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present

  - name: I want to create a folder
    file:
      path: /home/sow/myfolder
      state: directory

  - name: I want to copy a file into myfolder
    copy:
      src: mytestfile
      dest: /home/sow/myfolder

  - name: I want to copy index.j2 page into nodes side
    template:
       src: myindex.j2
       dest: /var/www/html/index.html
    notify: mywebserverstart

  - name: I want to download internet file
    get_url:
      url: https://askubuntu.com/questions/1452457/javac-11-to-17-in-ubuntu-20-04
      dest: /home/sow/myfolder/ubuntu
      force_basic_auth: yes
  handlers:
  - name: installtree
    apt:
      name: tree
      state: present