---
- hosts: 172.31.5.13
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: install webserver
    apt:
      name: apache2
      state: present
      
  - name: I want to create a folder
    file:
      path: /home/sow/myfolder
      state: directory

  - name: I want to copy a file into myfolder
    copy:
      src: mytestfile
      dest: /home/sow/myfolder