---
- hosts: all
  become: true
  tasks:
  - name: I want to install apache2 webserver
    apt:
      name: apache2
      state: present

  - name: I want to start apache2 webserver(sudo service apache2)
    service:
        name: apache2
        state: started
