---
- hosts: mywebservers
  become: true
 # gather_facts: yes
  tasks:
  - name: I want to install apache2 webserver
    apt:
      name: mywebpackageonubuntu
      state: present
    when: ansible_os_family=="Debian"

  - name: I want to start apache2 webserver(sudo service apache2)
    service:
        name: mywebpackageonubuntu
        state: started
    when: ansible_os_family=="Debian"

  - name: I want to install webserver on amazon nodes
    dnf:
        name: mywebpackageonredhat
        state: present
    when: ansible_os_family=="RedHat"

  - name: I want to start webserver on amazon nodes
    service:
        name: mywebpackageonredhat
        state: started
    when: ansible_os_family=="RedHat"

